### ISSUE TITLE
Run tiup check on Phytium arm64 platform must panic

### ISSUE THREAD

**Issue by chenmin1992** [pingcap/tiup#1337]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```bash
lscpu
架构：                           aarch64
CPU 运行模式：                   64-bit
字节序：                         Little Endian
CPU:                             128
在线 CPU 列表：                  0-127
每个核的线程数：                 1
每个座的核数：                   64
座：                             2
NUMA 节点：                      16
厂商 ID：                        Phytium
型号：                           3
型号名称：                       Phytium,FT-2500/128
步进：                           0x1
CPU 最大 MHz：                   2100.0000
CPU 最小 MHz：                   1100.0000
BogoMIPS：                       100.00
L1d 缓存：                       4 MiB
L1i 缓存：                       4 MiB
L2 缓存：                        64 MiB
L3 缓存：                        128 MiB
NUMA 节点0 CPU：                 0-7
NUMA 节点1 CPU：                 8-15
NUMA 节点2 CPU：                 16-23
NUMA 节点3 CPU：                 24-31
NUMA 节点4 CPU：                 32-39
NUMA 节点5 CPU：                 40-47
NUMA 节点6 CPU：                 48-55
NUMA 节点7 CPU：                 56-63
NUMA 节点8 CPU：                 64-71
NUMA 节点9 CPU：                 72-79
NUMA 节点10 CPU：                80-87
NUMA 节点11 CPU：                88-95
NUMA 节点12 CPU：                96-103
NUMA 节点13 CPU：                104-111
NUMA 节点14 CPU：                112-119
NUMA 节点15 CPU：                120-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

uname -a
Linux localhost.localdomain 4.19.90-21.2.ky10.aarch64 #1 SMP Tue Oct 27 16:46:15 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

tiup cluster check ./complex-mini.yaml --user root -p
```

2. What did you expect to see?
Run successfully.

3. What did you see instead?
A fatal error occured, logs as follow:
```
2021-04-28T13:58:34.515+0800	ERROR	SSHCommand	{"host": "10.7.24.243", "port": "22", "cmd": "export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /tmp/tiup/bin/insight", "error": "Process exited with status 2", "stdout": "", "stderr": "unexpected fault address 0xffff04750011\nfatal error: fault\n[signal SIGBUS: bus error code=0x1 addr=0xffff04750011 pc=0x4038d0]\ngoroutine 1 [running]:\nruntime.throw(0x613286, 0x5)\n\truntime/panic.go:774 +0x54 fp=0x40001d5850 sp=0x40001d5820 pc=0x42c01c\nruntime.sigpanic()\n\truntime/signal_unix.go:391 +0x434 fp=0x40001d5880 sp=0x40001d5850 pc=0x440b4c\nmemeqbody(0xffff04750010, 0x40001d58c0, 0x5, 0x40001d5800, 0x28, 0x5f494d445f, 0x40001d5a28, 0x50c534, 0xffff04750000, 0x1f, ...)\n\tinternal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40001d5890 sp=0x40001d5890 pc=0x4038d0\nbytes.Equal(...)\n\tbytes/bytes.go:20\ngithub.com/AstroProfundis/sysinfo.epsValid(0xffff04750000, 0x1f, 0x1f, 0x1f)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40001d58d0 sp=0x40001d5890 pc=0x50bc18\ngithub.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x4000010150, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40001d5a30 sp=0x40001d58d0 pc=0x50bf3c\ngithub.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40001d5b00 sp=0x40001d5a30 pc=0x50c534\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40001d5de0 sp=0x40001d5b00 pc=0x50c72c\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40001d5e20 sp=0x40001d5de0 pc=0x50fec0\ngithub.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x4000020c00, 0x0, 0x0, 0x0)\n\tgithub.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40001d5e90 sp=0x40001d5e20 pc=0x51d78c\nmain.main()\n\tgithub.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40001d5f50 sp=0x40001d5e90 pc=0x522688\nruntime.main()\n\truntime/proc.go:203 +0x23c fp=0x40001d5fd0 sp=0x40001d5f50 pc=0x42d8f4\nruntime.goexit()\n\truntime/asm_arm64.s:1128 +0x4 fp=0x40001d5fd0 sp=0x40001d5fd0 pc=0x456fcc\n"}
2021-04-28T13:58:34.515+0800	ERROR	CheckPoint	{"host": "10.7.24.243", "port": 22, "user": "root", "sudo": false, "cmd": "/tmp/tiup/bin/insight", "stdout": "", "stderr": "unexpected fault address 0xffff04750011\nfatal error: fault\n[signal SIGBUS: bus error code=0x1 addr=0xffff04750011 pc=0x4038d0]\ngoroutine 1 [running]:\nruntime.throw(0x613286, 0x5)\n\truntime/panic.go:774 +0x54 fp=0x40001d5850 sp=0x40001d5820 pc=0x42c01c\nruntime.sigpanic()\n\truntime/signal_unix.go:391 +0x434 fp=0x40001d5880 sp=0x40001d5850 pc=0x440b4c\nmemeqbody(0xffff04750010, 0x40001d58c0, 0x5, 0x40001d5800, 0x28, 0x5f494d445f, 0x40001d5a28, 0x50c534, 0xffff04750000, 0x1f, ...)\n\tinternal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40001d5890 sp=0x40001d5890 pc=0x4038d0\nbytes.Equal(...)\n\tbytes/bytes.go:20\ngithub.com/AstroProfundis/sysinfo.epsValid(0xffff04750000, 0x1f, 0x1f, 0x1f)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40001d58d0 sp=0x40001d5890 pc=0x50bc18\ngithub.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x4000010150, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40001d5a30 sp=0x40001d58d0 pc=0x50bf3c\ngithub.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40001d5b00 sp=0x40001d5a30 pc=0x50c534\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40001d5de0 sp=0x40001d5b00 pc=0x50c72c\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40001d5e20 sp=0x40001d5de0 pc=0x50fec0\ngithub.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x4000020c00, 0x0, 0x0, 0x0)\n\tgithub.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40001d5e90 sp=0x40001d5e20 pc=0x51d78c\nmain.main()\n\tgithub.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40001d5f50 sp=0x40001d5e90 pc=0x522688\nruntime.main()\n\truntime/proc.go:203 +0x23c fp=0x40001d5fd0 sp=0x40001d5f50 pc=0x42d8f4\nruntime.goexit()\n\truntime/asm_arm64.s:1128 +0x4 fp=0x40001d5fd0 sp=0x40001d5fd0 pc=0x456fcc\n", "error": "executor.ssh.execute_failed: Failed to execute command over SSH for 'root@10.7.24.243:22' {ssh_stderr: unexpected fault address 0xffff04750011\nfatal error: fault\n[signal SIGBUS: bus error code=0x1 addr=0xffff04750011 pc=0x4038d0]\ngoroutine 1 [running]:\nruntime.throw(0x613286, 0x5)\n\truntime/panic.go:774 +0x54 fp=0x40001d5850 sp=0x40001d5820 pc=0x42c01c\nruntime.sigpanic()\n\truntime/signal_unix.go:391 +0x434 fp=0x40001d5880 sp=0x40001d5850 pc=0x440b4c\nmemeqbody(0xffff04750010, 0x40001d58c0, 0x5, 0x40001d5800, 0x28, 0x5f494d445f, 0x40001d5a28, 0x50c534, 0xffff04750000, 0x1f, ...)\n\tinternal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40001d5890 sp=0x40001d5890 pc=0x4038d0\nbytes.Equal(...)\n\tbytes/bytes.go:20\ngithub.com/AstroProfundis/sysinfo.epsValid(0xffff04750000, 0x1f, 0x1f, 0x1f)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40001d58d0 sp=0x40001d5890 pc=0x50bc18\ngithub.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x4000010150, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40001d5a30 sp=0x40001d58d0 pc=0x50bf3c\ngithub.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40001d5b00 sp=0x40001d5a30 pc=0x50c534\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40001d5de0 sp=0x40001d5b00 pc=0x50c72c\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40001d5e20 sp=0x40001d5de0 pc=0x50fec0\ngithub.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x4000020c00, 0x0, 0x0, 0x0)\n\tgithub.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40001d5e90 sp=0x40001d5e20 pc=0x51d78c\nmain.main()\n\tgithub.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40001d5f50 sp=0x40001d5e90 pc=0x522688\nruntime.main()\n\truntime/proc.go:203 +0x23c fp=0x40001d5fd0 sp=0x40001d5f50 pc=0x42d8f4\nruntime.goexit()\n\truntime/asm_arm64.s:1128 +0x4 fp=0x40001d5fd0 sp=0x40001d5fd0 pc=0x456fcc\n, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /tmp/tiup/bin/insight}, cause: Process exited with status 2", "errorVerbose": "executor.ssh.execute_failed: Failed to execute command over SSH for 'root@10.7.24.243:22' {ssh_stderr: unexpected fault address 0xffff04750011\nfatal error: fault\n[signal SIGBUS: bus error code=0x1 addr=0xffff04750011 pc=0x4038d0]\ngoroutine 1 [running]:\nruntime.throw(0x613286, 0x5)\n\truntime/panic.go:774 +0x54 fp=0x40001d5850 sp=0x40001d5820 pc=0x42c01c\nruntime.sigpanic()\n\truntime/signal_unix.go:391 +0x434 fp=0x40001d5880 sp=0x40001d5850 pc=0x440b4c\nmemeqbody(0xffff04750010, 0x40001d58c0, 0x5, 0x40001d5800, 0x28, 0x5f494d445f, 0x40001d5a28, 0x50c534, 0xffff04750000, 0x1f, ...)\n\tinternal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40001d5890 sp=0x40001d5890 pc=0x4038d0\nbytes.Equal(...)\n\tbytes/bytes.go:20\ngithub.com/AstroProfundis/sysinfo.epsValid(0xffff04750000, 0x1f, 0x1f, 0x1f)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40001d58d0 sp=0x40001d5890 pc=0x50bc18\ngithub.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x4000010150, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40001d5a30 sp=0x40001d58d0 pc=0x50bf3c\ngithub.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40001d5b00 sp=0x40001d5a30 pc=0x50c534\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40001d5de0 sp=0x40001d5b00 pc=0x50c72c\ngithub.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x4000020cb0)\n\tgithub.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40001d5e20 sp=0x40001d5de0 pc=0x50fec0\ngithub.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x4000020c00, 0x0, 0x0, 0x0)\n\tgithub.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40001d5e90 sp=0x40001d5e20 pc=0x51d78c\nmain.main()\n\tgithub.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40001d5f50 sp=0x40001d5e90 pc=0x522688\nruntime.main()\n\truntime/proc.go:203 +0x23c fp=0x40001d5fd0 sp=0x40001d5f50 pc=0x42d8f4\nruntime.goexit()\n\truntime/asm_arm64.s:1128 +0x4 fp=0x40001d5fd0 sp=0x40001d5fd0 pc=0x456fcc\n, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /tmp/tiup/bin/insight}, cause: Process exited with status 2\n at github.com/pingcap/tiup/pkg/cluster/executor.(*EasySSHExecutor).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/executor/ssh.go:154\n at github.com/pingcap/tiup/pkg/cluster/executor.(*CheckPointExecutor).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/executor/checkpoint.go:85\n at github.com/pingcap/tiup/pkg/cluster/task.(*Shell).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/task/shell.go:42\n at github.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:85\n at github.com/pingcap/tiup/pkg/cluster/task.(*StepDisplay).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/task/step.go:87\n at github.com/pingcap/tiup/pkg/cluster/task.(*Parallel).Execute.func1()\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:134\n at runtime.goexit()\n\truntime/asm_arm64.s:1130", "__hash__": "68edc581eb12860f150abf89b72c26497d056578", "__func__": "github.com/pingcap/tiup/pkg/cluster/executor.(*CheckPointExecutor).Execute", "hit": false}
```

4. What version of TiUP are you using (`tiup --version`)?
v1.4.2

**Comment by AstroProfundis** [comment]
This is due to `sysinfo` we use panics on that test server. We don't yet know if that's a CPU related problem or a broken memory stick or something, or a pure software problem.
