### ISSUE TITLE
tiup-cluster errors deploying to ubuntu 20.04 arm64

### ISSUE THREAD

**Issue by kolbe** [pingcap/tiup#1396]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I tried to deploy a cluster of EC2 instances using the `ami-09d9c897fc36713bf` AMI on t4g.2xlarge arm64 instances.

2. What did you expect to see?

3. What did you see instead?

[tiup-cluster-debug-2021-06-02-20-06-47.log](https://github.com/pingcap/tiup/files/6587157/tiup-cluster-debug-2021-06-02-20-06-47.log)

```
Error: executor.ssh.execute_failed: Failed to execute command over SSH for 'ubuntu@10.0.3.162:22' {ssh_stderr: unexpected fault address 0xffffa4006011
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0xffffa4006011 pc=0x4038d0]

goroutine 1 [running]:
runtime.throw(0x613286, 0x5)
        runtime/panic.go:774 +0x54 fp=0x40000bf850 sp=0x40000bf820 pc=0x42c01c
runtime.sigpanic()
        runtime/signal_unix.go:391 +0x434 fp=0x40000bf880 sp=0x40000bf850 pc=0x440b4c
memeqbody(0xffffa4006010, 0x40000bf8c0, 0x5, 0x40000bf800, 0x28, 0x5f494d445f, 0x40000bfa28, 0x50c534, 0xffffa4006000, 0x1f, ...)
        internal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40000bf890 sp=0x40000bf890 pc=0x4038d0
bytes.Equal(...)
        bytes/bytes.go:20
github.com/AstroProfundis/sysinfo.epsValid(0xffffa4006000, 0x1f, 0x1f, 0x1f)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40000bf8d0 sp=0x40000bf890 pc=0x50bc18
github.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x40000a6140, 0x0, 0x0, 0x0, 0x0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40000bfa30 sp=0x40000bf8d0 pc=0x50bf3c
github.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40000bfb00 sp=0x40000bfa30 pc=0x50c534
github.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x40000f40b0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40000bfde0 sp=0x40000bfb00 pc=0x50c72c
github.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x40000f40b0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40000bfe20 sp=0x40000bfde0 pc=0x50fec0
github.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x40000f4000, 0x0, 0x0, 0x0)
        github.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40000bfe90 sp=0x40000bfe20 pc=0x51d78c
main.main()
        github.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40000bff50 sp=0x40000bfe90 pc=0x522688
runtime.main()
        runtime/proc.go:203 +0x23c fp=0x40000bffd0 sp=0x40000bff50 pc=0x42d8f4
runtime.goexit()
        runtime/asm_arm64.s:1128 +0x4 fp=0x40000bffd0 sp=0x40000bffd0 pc=0x456fcc
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H bash -c "/tmp/tiup/bin/insight"}, cause: exit status 2
```

4. What version of TiUP are you using (`tiup --version`)?

```
1.4.4 tiup
Go Version: go1.16.4
Git Ref: v1.4.4
GitHash: 0d0507355211fe16f95e1d00ed00c39f09c7565d
```

**Comment by kolbe** [comment]
This is a problem with https://github.com/pingcap/tidb-insight, in fact. It crashes on this platform when run under sudo but not when run as a regular user.

```
$ sudo /tmp/tiup/bin/insight
unexpected fault address 0xffffa065e011
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0xffffa065e011 pc=0x4038d0]

goroutine 1 [running]:
runtime.throw(0x613286, 0x5)
        runtime/panic.go:774 +0x54 fp=0x40000c1850 sp=0x40000c1820 pc=0x42c01c
runtime.sigpanic()
        runtime/signal_unix.go:391 +0x434 fp=0x40000c1880 sp=0x40000c1850 pc=0x440b4c
memeqbody(0xffffa065e010, 0x40000c18c0, 0x5, 0x40000c1800, 0x28, 0x5f494d445f, 0x40000c1a28, 0x50c534, 0xffffa065e000, 0x1f, ...)
        internal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40000c1890 sp=0x40000c1890 pc=0x4038d0
bytes.Equal(...)
        bytes/bytes.go:20
github.com/AstroProfundis/sysinfo.epsValid(0xffffa065e000, 0x1f, 0x1f, 0x1f)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40000c18d0 sp=0x40000c1890 pc=0x50bc18
github.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x40000a8140, 0x0, 0x0, 0x0, 0x0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40000c1a30 sp=0x40000c18d0 pc=0x50bf3c
github.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40000c1b00 sp=0x40000c1a30 pc=0x50c534
github.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x40000f60b0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40000c1de0 sp=0x40000c1b00 pc=0x50c72c
github.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x40000f60b0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40000c1e20 sp=0x40000c1de0 pc=0x50fec0
github.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x40000f6000, 0x0, 0x0, 0x0)
        github.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40000c1e90 sp=0x40000c1e20 pc=0x51d78c
main.main()
        github.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40000c1f50 sp=0x40000c1e90 pc=0x522688
runtime.main()
        runtime/proc.go:203 +0x23c fp=0x40000c1fd0 sp=0x40000c1f50 pc=0x42d8f4
runtime.goexit()
        runtime/asm_arm64.s:1128 +0x4 fp=0x40000c1fd0 sp=0x40000c1fd0 pc=0x456fcc
$ echo $?
2
```

```
$ /tmp/tiup/bin/insight
{
  "meta": {
    "timestamp": "2021-06-03T04:58:41.038860816Z",
    "uptime": 2394.15,
    "idle_time": 19108.74,
    "sysinfo_ver": "0.9.3",
    "git_branch": "heads/v0.3.2",
    "git_commit": "v0.3.2",
    "go_version": "go1.13.10 linux/arm64",
    "tidb": null,
    "tikv": null,
    "pd": null
  },
  "sysinfo": {
    "node": {
      "hostname": "ip-10-0-2-206",
      "machineid": "eb6361e1c42d415abd9a8fe62a839fb4",
      "timezone": "Etc/UTC"
    },
    "os": {
      "name": "Ubuntu 20.04.2 LTS",
      "vendor": "ubuntu",
      "version": "20.04",
      "release": "20.04.2"
    },
    "kernel": {
      "release": "5.4.0-1045-aws",
      "version": "#47-Ubuntu SMP Tue Apr 13 07:04:23 UTC 2021",
      "architecture": "aarch64"
    },
    "product": {
      "name": "t4g.2xlarge",
      "vendor": "Amazon EC2"
    },
    "board": {
      "vendor": "Amazon EC2",
      "assettag": "i-065d6b920d7be7ecc"
    },
    "chassis": {
      "type": 1,
      "vendor": "Amazon EC2",
      "assettag": "Amazon EC2"
    },
    "bios": {
      "vendor": "Amazon EC2",
      "version": "1.0",
      "date": "11/1/2018"
    },
    "cpu": {
      "threads": 8
    },
    "memory": {
      "size": 31717
    },
    "storage": [
      {
        "name": "nvme0n1",
        "model": "Amazon Elastic Block Store",
        "serial": "vol0129d4919ce22fda4",
        "size": 68
      }
    ],
    "network": [
      {
        "name": "ens5",
        "driver": "ena",
        "macaddress": "06:24:f2:b6:7f:49",
        "ipaddress": [
          "10.0.2.206/24",
          "fe80::424:f2ff:feb6:7f49/64"
        ],
        "mtu": 9001
      }
    ]
  },
  "ntp": {
    "version": "exec: \"ntpq\": executable file not found in $PATH"
  },
  "partitions": [
    {
      "name": "nvme0n1",
      "mount": {},
      "sectors": 134217728,
      "size": 68719476736,
      "subdev": [
        {
          "name": "nvme0n1p1",
          "partition": true,
          "mount": {},
          "uuid": "cb9103d6-ca5d-4862-9bc7-41fa9d819898",
          "sectors": 134010847,
          "size": 68613553664
        },
        {
          "name": "nvme0n1p15",
          "partition": true,
          "mount": {
            "mount_point": "/boot/efi",
            "filesystem": "vfat",
            "mount_options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro"
          },
          "uuid": "7CB3-16E6",
          "sectors": 202753,
          "size": 103809536
        }
      ],
      "rotational": "0"
    },
    {
      "name": "md0",
      "mount": {},
      "rotational": "1"
    }
  ],
  "epoll_exclusive": true
}
$ echo $?
0
```

**Comment by AstroProfundis** [comment]
This should already been fixed.
