### ISSUE TITLE
"tiup cluster check" failed in arm64 platform.

### ISSUE THREAD

**Issue by jiayang-zheng** [pingcap/tiup#1411]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I try to do a tiup cluster check before deploy in arm64 platform.
"$ tiup cluster check ./topology.yaml --user root -p"

2. What did you expect to see?
The Tiup Check works successfully.

3. What did you see instead?
[root@test28 ~]# tiup cluster check ./topology.yaml --user root -p
Starting component `cluster`: /root/.tiup/components/cluster/v1.4.4/tiup-cluster check ./topology.yaml --user root -p
Input SSH password:
+ Download necessary tools
  - Downloading check tools for linux/arm64 ... Done
+ Collect basic system information
+ Collect basic system information
  - Getting system info of 10.9.20.28:22 ... ⠦ CopyComponent: component=insight, version=, remote=10.9.20.28:/tmp/tiup os=linux, arch=arm64
+ Collect basic system information
  - Getting system info of 10.9.20.28:22 ... Error
  - Getting system info of 10.9.20.29:22 ... Error
  - Getting system info of 10.9.20.30:22 ... Error

Error: executor.ssh.execute_failed: Failed to execute command over SSH for 'root@10.9.20.29:22' {ssh_stderr: unexpected fault address 0xffff4e5c0011
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0xffff4e5c0011 pc=0x4038d0]
goroutine 1 [running]:
runtime.throw(0x613286, 0x5)
        runtime/panic.go:774 +0x54 fp=0x40001d5850 sp=0x40001d5820 pc=0x42c01c
runtime.sigpanic()
        runtime/signal_unix.go:391 +0x434 fp=0x40001d5880 sp=0x40001d5850 pc=0x440b4c
memeqbody(0xffff4e5c0010, 0x40001d58c0, 0x5, 0x40001d5800, 0x28, 0x5f494d445f, 0x40001d5a28, 0x50c534, 0xffff4e5c0000, 0x1f, ...)
        internal/bytealg/equal_arm64.s:112 +0xd8 fp=0x40001d5890 sp=0x40001d5890 pc=0x4038d0
bytes.Equal(...)
        bytes/bytes.go:20
github.com/AstroProfundis/sysinfo.epsValid(0xffff4e5c0000, 0x1f, 0x1f, 0x1f)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:53 +0x80 fp=0x40001d58d0 sp=0x40001d5890 pc=0x50bc18
github.com/AstroProfundis/sysinfo.getStructureTableAddressEFI(0x4000010150, 0x0, 0x0, 0x0, 0x0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:85 +0x274 fp=0x40001d5a30 sp=0x40001d58d0 pc=0x50bf3c
github.com/AstroProfundis/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:138 +0x10c fp=0x40001d5b00 sp=0x40001d5a30 pc=0x50c534
github.com/AstroProfundis/sysinfo.(*SysInfo).getMemoryInfo(0x4000020cb0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/memory.go:164 +0x54 fp=0x40001d5de0 sp=0x40001d5b00 pc=0x50c72c
github.com/AstroProfundis/sysinfo.(*SysInfo).GetSysInfo(0x4000020cb0)
        github.com/AstroProfundis/sysinfo@v0.0.0-20210201035811-eb96b87c86b3/sysinfo.go:33 +0x58 fp=0x40001d5e20 sp=0x40001d5de0 pc=0x50fec0
github.com/pingcap/tidb-insight/collector/insight.(*InsightInfo).GetInfo(0x4000020c00, 0x0, 0x0, 0x0)
        github.com/pingcap/tidb-insight@/collector/insight/insight.go:62 +0xd4 fp=0x40001d5e90 sp=0x40001d5e20 pc=0x51d78c
main.main()
        github.com/pingcap/tidb-insight@/collector/collector.go:38 +0x70 fp=0x40001d5f50 sp=0x40001d5e90 pc=0x522688
runtime.main()
        runtime/proc.go:203 +0x23c fp=0x40001d5fd0 sp=0x40001d5f50 pc=0x42d8f4
runtime.goexit()
        runtime/asm_arm64.s:1128 +0x4 fp=0x40001d5fd0 sp=0x40001d5fd0 pc=0x456fcc
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /tmp/tiup/bin/insight}, cause: Process exited with status 2

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2021-06-07-22-42-57.log.
Error: run `/root/.tiup/components/cluster/v1.4.4/tiup-cluster` (wd:/root/.tiup/data/SZezYQA) failed: exit status 1

----> It looks that the /tmp/tiup/bin/insight does not work fine.

4. What version of TiUP are you using (`tiup --version`)?
1.4.4 tiup
Go Version: go1.16.4
Git Ref: v1.4.4
GitHash: 0d0507355211fe16f95e1d00ed00c39f09c7565d

**Comment by 9547** [comment]
dup to https://github.com/pingcap/tidb-insight/issues/53. And could you please give more information about the hardware/os/...

**Comment by jiayang-zheng** [comment]
I ran on Kylin OS on Phytium CPU.
[root@test28 ~]# cat /etc/kylin-release
Kylin Linux Advanced Server release V10 (Tercel)

[root@test28 ~]# uname -a
Linux test28 4.19.90-21.2.ky10.aarch64 #1 SMP Tue Oct 27 16:46:15 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

[root@test28 ~]# lscpu
架构：                           aarch64
CPU 运行模式：                   64-bit
字节序：                         Little Endian
CPU:                             128
在线 CPU 列表：                  0-127
每个核的线程数：                 1
每个座的核数：                   8
座：                             16
NUMA 节点：                      16
厂商 ID：                        Phytium
型号：                           3
型号名称：                       Phytium,FT-2500/128
步进：                           0x1
CPU 最大 MHz：                   2100.0000
CPU 最小 MHz：                   1100.0000
BogoMIPS：                       100.00
L1d 缓存：                       4 MiB
L1i 缓存：                       6 MiB
L2 缓存：                        64 MiB
L3 缓存：                        128 MiB
NUMA 节点0 CPU：                 0-7
NUMA 节点1 CPU：                 8-15
NUMA 节点2 CPU：                 16-23
NUMA 节点3 CPU：                 24-31
NUMA 节点4 CPU：                 32-39
NUMA 节点5 CPU：                 40-47
NUMA 节点6 CPU：                 48-55
NUMA 节点7 CPU：                 56-63
NUMA 节点8 CPU：                 64-71
NUMA 节点9 CPU：                 72-79
NUMA 节点10 CPU：                80-87
NUMA 节点11 CPU：                88-95
NUMA 节点12 CPU：                96-103
NUMA 节点13 CPU：                104-111
NUMA 节点14 CPU：                112-119
NUMA 节点15 CPU：                120-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

**Comment by jiayang-zheng** [comment]
I tried to run the Check command in "tidb" user, looks good.
So the /tmp/tiup/bin/insight might not work fine in root?
[tidb@test28 ~]$ /tmp/tiup/bin/insight
{
  "meta": {
    "timestamp": "2021-06-08T08:13:23.350982845+08:00",
    "uptime": 31305.98,
    "idle_time": 4006066.12,
    "sysinfo_ver": "0.9.3",
    "git_branch": "heads/v0.3.2",
    "git_commit": "v0.3.2",
    "go_version": "go1.13.10 linux/arm64",
    "tidb": null,
    "tikv": null,
    "pd": null
  },
  "sysinfo": {
    "node": {
      "hostname": "test28",
      "machineid": "c64416f542e249b192f3e08eff52ceff",
      "timezone": "Asia/Shanghai"
    },
    "os": {
      "name": "Kylin Linux Advanced Server V10 (Tercel)",
      "vendor": "kylin",
      "version": "V10"
    },
    "kernel": {
      "release": "4.19.90-21.2.ky10.aarch64",
      "version": "#1 SMP Tue Oct 27 16:46:15 CST 2020",
      "architecture": "aarch64"
    },
    "product": {},
    "board": {},
    "chassis": {
      "type": 23,
      "vendor": "\u0005"
    },
    "bios": {
      "vendor": "ZD-TECH",
      "version": "KL4.26.UEFI.S.020.210331.D",
      "date": "03/31/21 19:40:18"
    },
    "cpu": {
      "model": "Phytium,FT-2500/128",
      "threads": 128
    },
    "memory": {
      "size": 260293,
      "swap": 4095
    },
    "storage": [
      {
        "name": "sda",
        "driver": "sd",
        "vendor": "ATA",
        "model": "INTEL SSDSC2KB48",
        "serial": "BTYF924103CJ480BGN",
        "size": 480
      },
      {
        "name": "sdb",
        "driver": "sd",
        "vendor": "AVAGO",
        "model": "MR9361-8i",
        "serial": "600605b00fa03a502548149622a59b11",
        "size": 8000
      },
      {
        "name": "sdc",
        "driver": "sd",
        "vendor": "AVAGO",
        "model": "MR9361-8i",
        "serial": "600605b00fa03a503cf9c9ce9f9c940e",
        "size": 999
      }
    ],
    "network": [
      {
        "name": "enp10s0f0",
        "driver": "i40e",
        "macaddress": "00:91:10:00:14:de",
        "mtu": 1500
      },
      {
        "name": "enp10s0f1",
        "driver": "i40e",
        "macaddress": "00:91:10:00:14:df",
        "ipaddress": [
          "10.9.20.28/24",
          "fe80::c3b3:8bcd:33ae:cae7/64"
        ],
        "port": "fibre",
        "speed": 10000,
        "mtu": 1500
      },
      {
        "name": "enp11s0f0",
        "driver": "igb",
        "macaddress": "00:91:10:00:1b:a0",
        "ipaddress": [
          "10.9.1.28/24",
          "fe80::291:10ff:fe00:1ba0/64"
        ],
        "port": "tp",
        "speed": 1000,
        "mtu": 1500
      },
      {
        "name": "enp11s0f1",
        "driver": "igb",
        "macaddress": "00:91:10:00:1b:a1",
        "port": "tp",
        "speed": 1000,
        "mtu": 1500
      }
    ]
  },
  "ntp": {
    "version": "ntpd 4.2.8p13@1.3847-o Tue Mar 17 12:53:17 UTC 2020 (1)",
    "sync": "sync_ntp",
    "stratum": 3,
    "offset": 1.287299,
    "status": "0618"
  },
  "partitions": [
    {
      "name": "dm-1",
      "mount": {},
      "uuid": "7b69c16f-984c-4f6c-a650-b43d5aa7c153",
      "sectors": 8388608,
      "size": 4294967296,
      "slave_of": [
        "sda3"
      ],
      "rotational": "0"
    },
    {
      "name": "sdb",
      "mount": {},
      "sectors": 15625879552,
      "size": 8000450330624,
      "rotational": "1"
    },
    {
      "name": "dm-2",
      "mount": {
        "mount_point": "/backup",
        "filesystem": "xfs",
        "mount_options": "rw,relatime,attr2,inode64,noquota"
      },
      "uuid": "db6249fa-cba8-4326-ac9e-45523c1d6c42",
      "sectors": 104857600,
      "size": 53687091200,
      "slave_of": [
        "sda3"
      ],
      "rotational": "0"
    },
    {
      "name": "dm-0",
      "mount": {
        "mount_point": "/",
        "filesystem": "xfs",
        "mount_options": "rw,relatime,attr2,inode64,noquota"
      },
      "uuid": "ef6e44e0-39ea-4c84-b977-38e1aa24ed49",
      "sectors": 821944320,
      "size": 420835491840,
      "slave_of": [
        "sda3"
      ],
      "rotational": "0"
    },
    {
      "name": "sdc",
      "mount": {},
      "sectors": 1952448512,
      "size": 999653638144,
      "subdev": [
        {
          "name": "sdc1",
          "partition": true,
          "mount": {
            "mount_point": "/data1",
            "filesystem": "ext4",
            "mount_options": "rw,noatime,nodelalloc,stripe=64"
          },
          "uuid": "3f2ea4ff-0a10-4d24-89d2-47696c2d15bb",
          "sectors": 1952444416,
          "size": 999651540992
        }
      ],
      "rotational": "1"
    },
    {
      "name": "sda",
      "mount": {},
      "sectors": 937703088,
      "size": 480103981056,
      "subdev": [
        {
          "name": "sda2",
          "partition": true,
          "mount": {
            "mount_point": "/boot",
            "filesystem": "xfs",
            "mount_options": "rw,relatime,attr2,inode64,noquota"
          },
          "uuid": "5ab043e5-742d-4474-bb1a-d75cff37c2b6",
          "sectors": 2097152,
          "size": 1073741824
        },
        {
          "name": "sda3",
          "partition": true,
          "mount": {},
          "sectors": 935192576,
          "size": 478818598912
        },
        {
          "name": "sda1",
          "partition": true,
          "mount": {
            "mount_point": "/boot/efi",
            "filesystem": "vfat",
            "mount_options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro"
          },
          "uuid": "7759-5BD5",
          "sectors": 409600,
          "size": 209715200
        }
      ],
      "rotational": "0"
    }
  ],
  "epoll_exclusive": true
}

**Comment by AstroProfundis** [comment]
This seems to be a dupe of #1337
