### ISSUE TITLE
Tiup starts failed for the latest version of TiDB

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tiup#1921]
## General Question

I am trying to start the playground for the latest dev version of TiDB on Ubuntu 16.04, but it fails. 

```shell
$ tiup playground v6.2.0-alpha-nightly-20220615
tiup is checking updates for component playground ...
Starting component `playground`: /home/jinsheng/.tiup/components/playground/v1.10.1/tiup-playground v6.2.0-alpha-nightly-20220615
Playground Bootstrapping...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe63e64]

goroutine 1 [running]:
main.(*Playground).terminate(0xc0006d0f20, 0x9)
        github.com/pingcap/tiup/components/playground/playground.go:990 +0x364
main.execute.func3(0xc00069c500?, {0xc0004e43d0, 0x1, 0x1?})
        github.com/pingcap/tiup/components/playground/main.go:291 +0x912
github.com/spf13/cobra.(*Command).execute(0xc00069c500, {0xc0001bc010, 0x1, 0x1})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00069c500)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
main.execute()
        github.com/pingcap/tiup/components/playground/main.go:352 +0x1032
main.main()
        github.com/pingcap/tiup/components/playground/main.go:629 +0x3f
```

**Comment by qqqdan** [comment]
Duplicate with https://github.com/pingcap/tiup/issues/2023
