### ISSUE TITLE
tiup playground panic when using db.host

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tiup#1968]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```bash
➜  tiup -v
1.9.3 tiup
Go Version: go1.17.7
Git Ref: v1.9.3
GitHash: f523cd5e051d0001e25d5a8b2c0d5d3ff058a5d5



➜  tiup playground v6.1.0 --host 0.0.0.0 --without-monitor --tiflash 0 --pd.config pd.toml --kv.config tikv.toml --db.host '::1'
tiup is checking updates for component playground ...
Starting component `playground`: /Users/jujiajia/.tiup/components/playground/v1.10.2/tiup-playground /Users/jujiajia/.tiup/components/playground/v1.10.2/tiup-playground v6.1.0 --host [0.0.0.0](http://0.0.0.0/) --without-monitor --tiflash 0 --pd.config pd.toml --kv.config tikv.toml --db.host ::1
panic: can't get a free port
goroutine 1 [running]:
[github.com/pingcap/tiup/pkg/utils.MustGetFreePort(...)](http://github.com/pingcap/tiup/pkg/utils.MustGetFreePort(...))
	[github.com/pingcap/tiup/pkg/utils/freeport.go:42](http://github.com/pingcap/tiup/pkg/utils/freeport.go:42)
[github.com/pingcap/tiup/components/playground/instance.NewTiDBInstance](http://github.com/pingcap/tiup/components/playground/instance.NewTiDBInstance)({0x0, 0x0}, {0x14000046810, 0x29}, {0x16b1cb4ec, 0x3}, {0x0, 0x0}, 0x0, 0x1400000f238?, ...)
	[github.com/pingcap/tiup/components/playground/instance/tidb.go:46](http://github.com/pingcap/tiup/components/playground/instance/tidb.go:46) +0x1c8
main.(*Playground).addInstance(0x1400002ac60, {0x1055ddf7f, 0x4}, {{0x0, 0x0}, {0x0, 0x0}, 0x1, {0x16b1cb4ec, 0x3}, ...})
	[github.com/pingcap/tiup/components/playground/playground.go:653](http://github.com/pingcap/tiup/components/playground/playground.go:653) +0x5ec
main.(*Playground).bootCluster(0x1400002ac60, {0x1059975a8, 0x14000099aa0}, 0x1059884a0?, 0x1060bab20)
	[github.com/pingcap/tiup/components/playground/playground.go:811](http://github.com/pingcap/tiup/components/playground/playground.go:811) +0x5f8
main.execute.func3(0x1400023f680?, {0x1400025bb00, 0x1, 0xc?})
	[github.com/pingcap/tiup/components/playground/main.go:287](http://github.com/pingcap/tiup/components/playground/main.go:287) +0x880
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0x1400023f680, {0x14000194de0, 0xc, 0xc})
	[github.com/spf13/cobra@v1.4.0/command.go:856](http://github.com/spf13/cobra@v1.4.0/command.go:856) +0x4c4
[github.com/spf13/cobra.(*Command).ExecuteC(0x1400023f680)](http://github.com/spf13/cobra.(*Command).ExecuteC(0x1400023f680))
	[github.com/spf13/cobra@v1.4.0/command.go:974](http://github.com/spf13/cobra@v1.4.0/command.go:974) +0x354
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	[github.com/spf13/cobra@v1.4.0/command.go:902](http://github.com/spf13/cobra@v1.4.0/command.go:902)
main.execute()
	[github.com/pingcap/tiup/components/playground/main.go:352](http://github.com/pingcap/tiup/components/playground/main.go:352) +0xbec
main.main()
	[github.com/pingcap/tiup/components/playground/main.go:629](http://github.com/pingcap/tiup/components/playground/main.go:629) +0x30
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by nexustar** [comment]
tidb do not support ipv6 https://github.com/pingcap/tidb/issues/11701
