### ISSUE TITLE
tiup playground panic

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tiup#538]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
goroutine 332 [running]:
github.com/pingcap/tiup/components/playground/instance.(*Process).Wait(0x0, 0x0, 0x0)
	github.com/pingcap/tiup@/components/playground/instance/process.go:30 +0x22
main.(*Playground).bootCluster.func7.1(0xc000483f68, 0x0)
	github.com/pingcap/tiup@/components/playground/playground.go:927 +0x4b
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002d80b8, 0xc0000e6460)
	golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
Error: run `/Users/zhouqiang/.tiup/components/playground/v1.0.7/tiup-playground` (wd:/Users/zhouqiang/.tiup/data/S38JQg7) failed: exit status 2

```
1. What did you do?

just start tiup playground like
`tiup playground --db.config tidb.toml --kv.config tikv.toml --pd.config pd.toml`

2. What did you expect to see?
start success

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
```
v1.0.7 tiup
Go Version: go1.13
Git Branch: v1.0
GitHash: 7f51794
```

**Comment by lonng** [comment]
@july2993 PTAL

**Comment by july2993** [comment]
This is caused by the tiflash is not started and we still `Wait` for it, only flash has this issue, I will fix it.
