### ISSUE TITLE
Search logs doesn't work in dashboard when deploying by tiup playground

### ISSUE THREAD

**Issue by baurine** [pingcap/tiup#570]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- Run cluster locally  by tiup playground with command `tiup playground nightly --tiflash 0 --monitor=false`
- Access the dashboard `http://127.0.0.1:2379/dashboard`
- Search logs in dashboard by default options

2. What did you expect to see?

A non-empty result table

3. What did you see instead?

An empty result table

More details: https://github.com/pingcap-incubator/tidb-dashboard/issues/665

4. What version of TiUP are you using (`tiup --version`)?

```
> tiup --version
v1.0.7 tiup
Go Version: go1.13
Git Branch: v1.0
GitHash: 7f51794
```

5. Reason

After investigating, the reason is the log files contain illegal format lines in the beginning.

For example, the following is the tidb.log contents:

```
Starting component `tidb`: /Users/baurine/.tiup/components/tidb/nightly/tidb-server -P 4000 --store=tikv --host=127.0.0.1 --status=10080 --path=127.0.0.1:2379 --log-file=/Users/baurine/.tiup/data/S3e0t3c/tidb-0/tidb.log
[2020/07/03 11:17:41.055 +08:00] [INFO] [printer.go:42] ["Welcome to TiDB."] ["Release Version"=v4.0.0-beta.2-711-gf31298f5b-dirty] [Edition=Community] ["Git Commit Hash"=f31298f5bb55d0c37dcd95c30d0253deef6b850e] ["Git Branch"=master] ["UTC Build Time"="2020-07-03 02:55:56"] [GoVersion=go1.14.1] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2020/07/03 11:17:41.055 +08:00] [INFO] [trackerRecorder.go:28] ["Mem Profile Tracker started"]
```

**Comment by baurine** [comment]
This issue can be resolved by PR #588 which is almost done. I checked that the log file doesn't include the invalid line anymore.

But playground crashed after starting a moment in my local, following is the error outputs:

```
> make
> cp ./bin/tiup-playground ~/.tiup/components/playground/v1.0.7/
> ./bin/tiup playground nightly --tiflash 0 --monitor=false    
Starting component `playground`:  nightly --tiflash 0 --monitor=false
Playground Bootstrapping...
Start pd instance...
Start tikv instance...
Start tidb instance...
............................................................To view the dashboard: http://127.0.0.1:2379/dashboard
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1addd56]

goroutine 1 [running]:
main.(*Playground).bootCluster(0xc0002be000, 0xc0002b5f60, 0xc000001980, 0x0, 0x0)
        /Users/baurine/Codes/Work/tiup/components/playground/playground.go:795 +0x1726
main.execute.func2(0xc0001b9600, 0xc000051f00, 0x1, 0x4, 0x0, 0x0)
        /Users/baurine/Codes/Work/tiup/components/playground/main.go:128 +0x179
github.com/spf13/cobra.(*Command).execute(0xc0001b9600, 0xc00003a0b0, 0x4, 0x4, 0xc0001b9600, 0xc00003a0b0)
        /Users/baurine/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b9600, 0xc00029bf00, 0x1, 0x1)
        /Users/baurine/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/baurine/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.execute(0xc00029bf48, 0x1043237)
        /Users/baurine/Codes/Work/tiup/components/playground/main.go:162 +0xb91
main.main()
        /Users/baurine/Codes/Work/tiup/components/playground/main.go:270 +0x26
Error: run `` (wd:/Users/baurine/.tiup/data/S4KT4k5) failed: exit status 2
```

@lucklove
