### ISSUE TITLE
tiup playground panic 

### ISSUE THREAD

**Issue by lhy1024** [pingcap/tiup#751]
```
Found playground newer version:

    The latest version:         v1.1.1
    Local installed version:    v1.0.9
    Update current component:   tiup update playground
    Update all components:      tiup update --all

Starting component `playground`: /home/lhy1024/.tiup/components/playground/v1.0.9/tiup-playground
Use the latest stable version: v4.0.5

    Specify version manually:   tiup playground <version>
    The stable version:         tiup playground v4.0.0
    The nightly version:        tiup playground nightly

Playground Bootstrapping...
The component `prometheus` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/prometheus-v4.0.5-linux-amd64.tar.gz 39.84 MiB / 39.84 MiB 100.00% 53.09 MiB p/s                       
download https://tiup-mirrors.pingcap.com/grafana-v4.0.5-linux-amd64.tar.gz 54.24 MiB / 54.24 MiB 100.00% 39.13 MiB p/s                          
Start pd instance...
The component `pd` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/pd-v4.0.5-linux-amd64.tar.gz 37.74 MiB / 37.74 MiB 100.00% 45.67 MiB p/s                               
Start tikv instance...
The component `tikv` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tikv-v4.0.5-linux-amd64.tar.gz 134.43 MiB / 134.43 MiB 100.00% 35.60 MiB p/s                           
Start tidb instance...
The component `tidb` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tidb-v4.0.5-linux-amd64.tar.gz 38.75 MiB / 38.75 MiB 100.00% 57.01 MiB p/s                             
..
Waiting for tikv 127.0.0.1:20160 ready 
Start tiflash instance...
TiFlash failed to start. no version: v4.0.5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xecbcd2]

goroutine 737 [running]:
github.com/pingcap/tiup/components/playground/instance.(*TiFlashInstance).Wait(0xc0003480d0, 0x139aac0, 0xc000044158, 0x0, 0xc00073b6c8)
	<autogenerated>:1 +0x32
main.(*Playground).addWaitInstance.func1(0xc00073b768, 0x0)
	github.com/pingcap/tiup@/components/playground/playground.go:409 +0x6c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0003600b0, 0xc008d30380)
	golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
Error: run `/home/lhy1024/.tiup/components/playground/v1.0.9/tiup-playground` (wd:/home/lhy1024/.tiup/data/S9WOf8F) failed: exit status 2

```

because there no be available TiFlash

**Comment by 9547** [comment]
duplicate to #728
